cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-southeast-2
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

spring:
  main:
    allow-bean-definition-overriding: true